### ISSUE TITLE
From /2018/11/07/hexo-build/

### ISSUE THREAD

**Issue by Geno1024** [lotuny/lotuny.github.io#3]
> GitHub 账号（已经创建了 SSH 密钥对并配置完成）

那个，你后面用的 HTTPS 是肿么肥四
> 路径映射问题。

这个用多了就知道了
> Markdown 有序列表：为啥我 IDE 预览和网页浏览的效果不一样！

因为 Md 没有标准啊，所以就二三三了，基本原理都是转为 HTML（其实这转换器还挺简单的），然后各家搭配不同的 CSS 就……

**Comment by lotuny** [comment]
> 那个，你后面用的 HTTPS 是肿么肥四

直接从配置文件里复制粘贴来的，这么做好像也没问题。

> 因为 Md 没有标准啊，所以就二三三了，基本原理都是转为 HTML（其实这转换器还挺简单的），然后各家搭配不同的 CSS 就……

原来如此！

**Comment by Geno1024** [comment]
> 直接从配置文件里复制粘贴来的，这么做好像也没问题。

是的，没有问题，但是后面用 HTTPS 前面就没必要配 SSH 了啊，配了 SSH 后面就没必要用 HTTPS 去输入密码了啊（
