### ISSUE TITLE
From /2018/11/08/git-learning/

### ISSUE THREAD

**Issue by Geno1024** [lotuny/lotuny.github.io#4]
`git remote add <remote> <url>` 你好像忘了这个操作

以及可能需要稍微提一下 `git clone <url>`……

**Comment by lotuny** [comment]
我每次都是手动添加远程库……
那个`git clone <url>`有什么问题吗

**Comment by Geno1024** [comment]
`git clone` = `git init` + `git remote add` + `git pull`，“基本操作”应该加上这个（好吧，强迫症

**Comment by lotuny** [comment]
时至今日，我终于加上了。
